name: "refresh"

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'

jobs:
  aptb:
    uses: invalidunit/action/.github/workflows/aptb.yml@main
    with:
      _repo: https://huami1314.github.io/devrepo/
      _sleep: 0


  remove_all_old_actions:
    uses: invalidunit/action/.github/workflows/remove_all_actions.yml@main
